### ISSUE TITLE
When to Dispose / Create?

### ISSUE THREAD

**Issue by Lydecker** [DigitalStrawberry/ANE-HapticFeedback#1]
Hi - great ANE thanks!

Should we create a new generator EACH time we want to provide feedback in an app, and then dispose of EACH generator after we have triggered it, or should we create one generator at the start, prepare/trigger it multiple times, then dispose the single generator when the app closes?

Thanks

**Comment by marpies** [comment]
Thanks, we're glad you find it useful!

You should reuse the generator if possible. It's fine to release the generator if you don't plan to use it for a while (e.g. when leaving the section of your app where the feedback is provided) and then create it again when needed, but it shouldn't be done each time you trigger a feedback.
